from __future__ import annotations

import time
from typing import Any

from app.ai.providers.base import EditingAgentProvider


class MockEditingAgentProvider(EditingAgentProvider):
    """Deterministic local planner for UI development; it never invokes a third-party model."""

    def __init__(self, delay_seconds: float = 0.35) -> None:
        self.delay_seconds = max(0.0, delay_seconds)

    @property
    def name(self) -> str:
        return "mock_editing_agent"

    def plan_edit(
        self, *, system_prompt: str, user_prompt: str, tools: list[Any]
    ) -> tuple[list[dict[str, Any]], str | None]:
        del system_prompt, tools
        time.sleep(self.delay_seconds)
        # The worker already supplied a compact JSON context. This mock intentionally stays conservative.
        if "節奏" in user_prompt or "緊湊" in user_prompt:
            marker = '"clips":['
            if marker in user_prompt:
                # The concrete tool call is generated by parsing the first explicit clip object without guessing IDs.
                import json

                state = json.loads(user_prompt.split("TIMELINE_STATE (read-only):\n", 1)[1])
                for clip in state.get("clips", []):
                    if clip.get("track") == "main_video" and clip.get("enabled"):
                        start = float(clip["source_start"])
                        end = float(clip["source_end"])
                        if end - start > 1.0:
                            return ([{
                                "name": "trim_clip",
                                "arguments": {
                                    "clip_id": clip["clip_id"], "source_start": start + 0.15,
                                    "source_end": end - 0.15,
                                },
                            }], None)
        return [], "目前沒有足夠且已驗證的時間軸資訊可安全套用這項修改。"


class OpenAILangChainEditingAgentProvider(EditingAgentProvider):
    """LangChain adapter. All provider-specific tool-call shapes are normalised at this boundary."""

    def __init__(self, api_key: str | None, model: str) -> None:
        self.api_key = api_key
        self.model = model

    @property
    def name(self) -> str:
        return f"openai:{self.model}"

    def plan_edit(
        self, *, system_prompt: str, user_prompt: str, tools: list[Any]
    ) -> tuple[list[dict[str, Any]], str | None]:
        if not self.api_key:
            raise RuntimeError("OPENAI_API_KEY is required when MOCK_AI is disabled")
        from langchain_core.messages import HumanMessage, SystemMessage
        from langchain_openai import ChatOpenAI

        model = ChatOpenAI(model=self.model, api_key=self.api_key, temperature=0).bind_tools(tools)
        response = model.invoke([SystemMessage(content=system_prompt), HumanMessage(content=user_prompt)])
        calls = [
            {"name": item["name"], "arguments": dict(item.get("args", {}))}
            for item in (response.tool_calls or [])
        ]
        clarification = str(response.content).strip() if response.content else None
        return calls, clarification
