"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

const capabilities = [
  ["✦", "AI 粗剪", "自動標出靜音、贅詞與可省略段落；你永遠保有最後決定權。"],
  ["▣", "一鍵多平台", "一次生成 16:9、9:16、1:1，並保留各自的主角追蹤與安全區。"],
  ["◌", "本機先行", "素材可在瀏覽器本機快取並背景同步，不必先等大檔傳完。"],
] as const;

const workflow = ["拖入素材", "AI 提出可預覽的剪輯方案", "確認後匯出或發佈"];

export function MarketingHome() {
  const [ready, setReady] = useState(false);
  useEffect(() => setReady(true), []);
  return <main className="min-h-screen overflow-hidden bg-[#09090f] text-zinc-100 selection:bg-cyan-300 selection:text-zinc-950">
    <div aria-hidden className="pointer-events-none fixed inset-0 -z-0 bg-[radial-gradient(circle_at_18%_0%,rgba(34,211,238,.17),transparent_28%),radial-gradient(circle_at_80%_8%,rgba(217,70,239,.12),transparent_26%)]" />
    <header className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 md:px-10"><Link href="/" className="flex items-center gap-2 font-semibold tracking-tight"><span className="grid h-8 w-8 place-items-center rounded-xl bg-gradient-to-br from-cyan-200 to-violet-400 text-zinc-950 shadow-[0_0_24px_rgba(34,211,238,.35)]">V</span>VantaCut</Link><nav className="hidden items-center gap-6 text-sm text-zinc-400 md:flex"><a href="#how">怎麼運作</a><a href="#features">功能</a><a href="#trust">你的素材</a></nav><Link href="/studio" className="rounded-xl border border-cyan-200/40 bg-cyan-200/10 px-3 py-2 text-xs font-semibold text-cyan-100 transition hover:bg-cyan-200 hover:text-zinc-950">開啟工作室</Link></header>
    <section className="relative z-10 mx-auto grid max-w-7xl gap-10 px-5 pb-20 pt-14 md:grid-cols-[1.1fr_.9fr] md:px-10 md:pb-28 md:pt-24"><div className={`transition duration-700 ${ready ? "translate-y-0 opacity-100" : "translate-y-5 opacity-0"}`}><p className="inline-flex items-center gap-2 rounded-full border border-cyan-200/25 bg-cyan-200/10 px-3 py-1 text-xs text-cyan-100"><span className="h-1.5 w-1.5 rounded-full bg-cyan-200" />從素材到成片，不需要先學剪輯</p><h1 className="mt-5 max-w-3xl text-5xl font-semibold leading-[.98] tracking-[-.06em] text-white md:text-7xl">把你的故事，<br /><span className="bg-gradient-to-r from-cyan-200 via-sky-300 to-fuchsia-300 bg-clip-text text-transparent">剪成想被看完的樣子。</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-zinc-400">VantaCut 是為一般創作者設計的 AI 影片工作室。先讓 AI 做繁瑣工作，再由你用最少的步驟做出真正屬於你的版本。</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/studio" className="rounded-2xl bg-white px-5 py-3 text-sm font-bold text-zinc-950 transition hover:scale-[1.02]">免費開始剪輯 <span aria-hidden>→</span></Link><Link href="/studio?mode=demo" className="rounded-2xl border border-zinc-700 bg-zinc-900/70 px-5 py-3 text-sm font-semibold text-zinc-200 transition hover:border-zinc-500">先看互動範例</Link></div><p className="mt-3 text-xs text-zinc-500">不需先上傳大檔 · 本機快取優先 · 所有 AI 修改皆可復原</p></div>
      <div className={`relative transition delay-150 duration-700 ${ready ? "translate-y-0 opacity-100" : "translate-y-5 opacity-0"}`}><div className="absolute -inset-6 rounded-[3rem] bg-cyan-400/15 blur-3xl" /><div className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-zinc-900/80 p-4 shadow-2xl backdrop-blur"><div className="flex items-center justify-between border-b border-white/10 pb-3 text-xs"><span className="font-medium text-zinc-200">旅行 Vlog · Iceland</span><span className="rounded-full bg-emerald-300/15 px-2 py-1 text-emerald-200">AI 已準備</span></div><div className="mt-4 aspect-video rounded-2xl bg-[linear-gradient(135deg,#0e7490,#0f172a_45%,#581c87)] p-4"><div className="flex h-full flex-col justify-between rounded-xl border border-white/20 bg-black/15 p-3"><span className="w-fit rounded bg-black/40 px-2 py-1 text-[10px] text-cyan-50">9:16 · 主角已置中</span><div className="rounded-lg bg-black/30 px-3 py-2 text-center text-sm font-bold text-white">冰島自駕，最值得做的一件事</div></div></div><div className="mt-4 space-y-2"><div className="h-9 rounded-lg bg-blue-400/55" /><div className="h-9 rounded-lg border border-dashed border-rose-300/70 bg-rose-400/20" /><div className="h-9 w-2/3 rounded-lg bg-blue-400/55" /></div><div className="mt-3 flex justify-between text-[11px] text-zinc-400"><span>靜音、贅詞已標記</span><span>可一鍵採納或保留</span></div></div></div></section>
    <section id="how" className="relative z-10 border-y border-white/5 bg-white/[.02]"><div className="mx-auto max-w-7xl px-5 py-14 md:px-10"><p className="text-xs font-medium uppercase tracking-[.22em] text-cyan-300">少一點複雜，更多創作</p><div className="mt-7 grid gap-4 md:grid-cols-3">{workflow.map((step, index) => <article key={step} className="rounded-2xl border border-white/10 bg-zinc-950/50 p-5"><span className="text-sm text-cyan-200">0{index + 1}</span><h2 className="mt-8 text-xl font-semibold">{step}</h2><p className="mt-2 text-sm leading-6 text-zinc-400">{index === 0 ? "從手機、相機或電腦拖入影片，立即開始瀏覽。" : index === 1 ? "所有建議先顯示為 Ghost 提案，絕不蓋掉原始素材。" : "生成適合每個社群平台的比例，集中下載或排程發布。"}</p></article>)}</div></div></section>
    <section id="features" className="relative z-10 mx-auto max-w-7xl px-5 py-20 md:px-10"><div className="grid gap-4 md:grid-cols-3">{capabilities.map(([icon, title, text]) => <article key={title} className="rounded-3xl border border-white/10 bg-gradient-to-b from-white/[.07] to-transparent p-6"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-cyan-200/10 text-lg text-cyan-100">{icon}</span><h2 className="mt-6 text-lg font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-zinc-400">{text}</p></article>)}</div></section>
    <section id="trust" className="relative z-10 mx-auto max-w-4xl px-5 pb-20 text-center"><p className="text-sm font-semibold text-white">你掌控每一次變更</p><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-zinc-400">原始影片不會被覆寫。每次 AI 裁切、濾鏡與音訊處理都以可比較、可復原的非破壞性設定保存。</p><Link href="/studio" className="mt-7 inline-block rounded-2xl bg-gradient-to-r from-cyan-200 to-violet-300 px-5 py-3 text-sm font-bold text-zinc-950">開始第一支影片</Link></section>
    <footer className="relative z-10 border-t border-white/5 px-5 py-7 text-center text-xs text-zinc-600">VantaCut · AI-assisted, human-approved editing.</footer>
  </main>;
}
