"""add opted-in distributed render tracker tables

Revision ID: 0028_add_distributed_compute
Revises: 0027_add_virtual_avatar
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0028_add_distributed_compute"
down_revision = "0027_add_virtual_avatar"
branch_labels = None
depends_on = None

def _base_columns() -> list[sa.Column]:
    return [sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False)]

def upgrade() -> None:
    node_status = postgresql.ENUM("pending", "active", "paused", "banned", name="compute_node_status", create_type=False)
    batch_status = postgresql.ENUM("queued", "dispatching", "assembling", "completed", "failed", name="distributed_batch_status", create_type=False)
    node_status.create(op.get_bind(), checkfirst=True); batch_status.create(op.get_bind(), checkfirst=True)
    op.create_table("compute_nodes", *_base_columns(), sa.Column("owner_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("label", sa.String(160), nullable=False), sa.Column("public_key", sa.String(512), nullable=False), sa.Column("node_kind", sa.String(24), nullable=False, server_default="browser"), sa.Column("status", node_status, nullable=False, server_default="pending"), sa.Column("capabilities_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default="{}"), sa.Column("consent_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default="{}"), sa.Column("renderer_image_digest", sa.String(255)), sa.Column("last_heartbeat_at", sa.DateTime(timezone=True)), sa.Column("reputation_score", sa.Integer(), nullable=False, server_default="0"), sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"), sa.UniqueConstraint("public_key"))
    op.create_table("distributed_render_batches", *_base_columns(), sa.Column("render_job_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("owner_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("status", batch_status, nullable=False, server_default="queued"), sa.Column("chunk_seconds", sa.Integer(), nullable=False, server_default="5"), sa.Column("replication_factor", sa.Integer(), nullable=False, server_default="2"), sa.Column("manifest_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default="{}"), sa.Column("manifest_sha256", sa.String(64), nullable=False), sa.Column("final_output_key", sa.String(1000)), sa.Column("error_message", sa.Text()), sa.ForeignKeyConstraint(["render_job_id"], ["render_jobs.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="RESTRICT"), sa.UniqueConstraint("render_job_id"))
    op.create_table("distributed_render_chunks", *_base_columns(), sa.Column("batch_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("chunk_index", sa.Integer(), nullable=False), sa.Column("output_start_seconds", sa.Numeric(12, 3), nullable=False), sa.Column("output_end_seconds", sa.Numeric(12, 3), nullable=False), sa.Column("manifest_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default="{}"), sa.Column("manifest_sha256", sa.String(64), nullable=False), sa.Column("status", sa.String(24), nullable=False, server_default="queued"), sa.Column("required_replicas", sa.Integer(), nullable=False, server_default="2"), sa.Column("accepted_checksum", sa.String(64)), sa.Column("accepted_object_key", sa.String(1000)), sa.ForeignKeyConstraint(["batch_id"], ["distributed_render_batches.id"], ondelete="CASCADE"), sa.UniqueConstraint("batch_id", "chunk_index", name="uq_distributed_render_chunk_index"))
    op.create_table("distributed_render_assignments", *_base_columns(), sa.Column("chunk_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("node_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("ticket_nonce", sa.String(80), nullable=False), sa.Column("ticket_sha256", sa.String(64), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("status", sa.String(24), nullable=False, server_default="assigned"), sa.Column("output_checksum", sa.String(64)), sa.Column("decoded_fingerprint", sa.String(64)), sa.Column("renderer_image_digest", sa.String(255)), sa.Column("output_object_key", sa.String(1000)), sa.Column("node_signature", sa.Text()), sa.Column("error_message", sa.Text()), sa.ForeignKeyConstraint(["chunk_id"], ["distributed_render_chunks.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["node_id"], ["compute_nodes.id"], ondelete="CASCADE"), sa.UniqueConstraint("chunk_id", "node_id", name="uq_distributed_assignment_chunk_node"), sa.UniqueConstraint("ticket_nonce", name="uq_distributed_assignment_ticket_nonce"))
    op.create_table("compute_credit_ledger", *_base_columns(), sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("node_id", postgresql.UUID(as_uuid=True)), sa.Column("assignment_id", postgresql.UUID(as_uuid=True)), sa.Column("amount", sa.Integer(), nullable=False), sa.Column("event_type", sa.String(48), nullable=False), sa.Column("idempotency_key", sa.String(255), nullable=False), sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default="{}"), sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["node_id"], ["compute_nodes.id"], ondelete="SET NULL"), sa.ForeignKeyConstraint(["assignment_id"], ["distributed_render_assignments.id"], ondelete="SET NULL"), sa.UniqueConstraint("idempotency_key", name="uq_compute_credit_ledger_idempotency"))
    for table, columns in {"compute_nodes": ["owner_id", "status", "last_heartbeat_at"], "distributed_render_batches": ["render_job_id", "project_id", "owner_id", "status", "manifest_sha256"], "distributed_render_chunks": ["batch_id", "status", "manifest_sha256"], "distributed_render_assignments": ["chunk_id", "node_id", "expires_at", "status"], "compute_credit_ledger": ["user_id", "node_id", "assignment_id"]}.items():
        for column in columns: op.create_index(f"ix_{table}_{column}", table, [column])

def downgrade() -> None:
    for table in ["compute_credit_ledger", "distributed_render_assignments", "distributed_render_chunks", "distributed_render_batches", "compute_nodes"]: op.drop_table(table)
    postgresql.ENUM(name="distributed_batch_status").drop(op.get_bind(), checkfirst=True); postgresql.ENUM(name="compute_node_status").drop(op.get_bind(), checkfirst=True)
