"use client";

import { useEffect, useState } from "react";

import { FitnessHudCanvas, type FitnessHudStyle, type FitnessRepEvent } from "@/features/editor/fitness-hud-canvas";
import { authenticatedFetch } from "@/lib/api/authenticated-fetch";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
type Exercise = "squat" | "bench_press" | "deadlift";
interface FitnessRecord { status: "idle" | "queued" | "processing" | "completed" | "failed"; rep_count: number; events: FitnessRepEvent[]; fatigue_event?: { timeline_time: number; fatigue?: boolean } | null; error?: string; }

export function FitnessOverlayPanel({ timelineId, sourceAssetId, playheadTime }: { timelineId: string; userId: string; sourceAssetId?: string; playheadTime: number }) {
  const [exercise, setExercise] = useState<Exercise>("squat"); const [style, setStyle] = useState<FitnessHudStyle>("impact"); const [targetReps, setTargetReps] = useState(10); const [record, setRecord] = useState<FitnessRecord>({ status: "idle", rep_count: 0, events: [] });
  const refresh = async () => { const response = await authenticatedFetch(`${API_URL}/api/v1/timelines/${timelineId}/fitness-overlay`); if (response.ok) setRecord(await response.json() as FitnessRecord); };
  useEffect(() => { void refresh(); }, [timelineId]);
  useEffect(() => { if (record.status !== "queued" && record.status !== "processing") return; const id = window.setInterval(() => void refresh(), 2500); return () => window.clearInterval(id); }, [record.status]);
  const analyze = async () => { if (!sourceAssetId) return; setRecord((current) => ({ ...current, status: "queued", error: undefined })); try { const response = await authenticatedFetch(`${API_URL}/api/v1/timelines/${timelineId}/fitness-overlay`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ source_asset_id: sourceAssetId, exercise, hud_style: style, target_reps: targetReps, sample_every_n_frames: 3, fatigue_ratio: 1.25 }) }); const data = await response.json() as { detail?: string }; if (!response.ok) throw new Error(data.detail ?? "無法建立動作分析任務"); } catch (error) { setRecord((current) => ({ ...current, status: "failed", error: error instanceof Error ? error.message : "無法建立動作分析任務" })); } };
  const working = record.status === "queued" || record.status === "processing";
  return <section className="rounded-xl border border-orange-300/25 bg-zinc-950 p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="text-sm font-semibold text-orange-100">AI 動態計數與運動 UI</h2><p className="mt-1 text-xs text-zinc-400">MediaPipe Pose 追蹤週期動作；完成 rep 時顯示打擊數字，力竭慢速最後一組會加上紅色高光與 Bass Hit。</p></div><span className="rounded bg-orange-300/10 px-2 py-1 text-[10px] font-semibold text-orange-200">{working ? "分析中" : record.status === "completed" ? `${record.rep_count} REPS` : record.status === "failed" ? "失敗" : "待分析"}</span></div><div className="mt-3 grid grid-cols-3 gap-2">{([ ["squat", "深蹲"], ["bench_press", "臥推"], ["deadlift", "硬舉"] ] as const).map(([value, label]) => <button key={value} type="button" onClick={() => setExercise(value)} className={`rounded px-2 py-1.5 text-xs ${exercise === value ? "bg-orange-300 text-zinc-950" : "bg-zinc-800 text-zinc-300"}`}>{label}</button>)}</div><div className="mt-2 flex flex-wrap items-center gap-2"><select value={style} onChange={(event) => setStyle(event.target.value as FitnessHudStyle)} className="rounded border border-zinc-700 bg-zinc-900 px-2 py-1 text-xs text-zinc-100"><option value="impact">Impact 打擊感</option><option value="neon">Neon 霓虹</option><option value="minimal">Minimal 極簡</option></select><label className="text-xs text-zinc-300">目標 <input type="number" min={1} max={100} value={targetReps} onChange={(event) => setTargetReps(Math.max(1, Math.min(100, Number(event.target.value) || 1)))} className="ml-1 w-12 rounded border border-zinc-700 bg-zinc-900 px-1 py-1 text-center" /> reps</label></div><div className="mt-3"><FitnessHudCanvas events={record.events} targetReps={targetReps} style={style} currentTime={playheadTime} fatigueTime={record.fatigue_event?.timeline_time} /></div><button type="button" disabled={!sourceAssetId || working} onClick={() => void analyze()} className="mt-3 rounded bg-orange-300 px-3 py-2 text-xs font-bold text-zinc-950 disabled:opacity-45">{working ? "正在追蹤關節週期…" : "分析動作並套用 HUD"}</button>{!sourceAssetId && <p className="mt-2 text-xs text-amber-300">目前時間軸找不到來源影片，無法開始姿勢分析。</p>}{record.fatigue_event?.fatigue && <p className="mt-2 text-xs text-red-300">已偵測最後一組顯著放慢：導出時會加入紅色邊緣與重低音。</p>}{record.error && <p className="mt-2 text-xs text-rose-300">{record.error}</p>}</section>;
}
