"use client";
import { useState } from "react";
const API = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000";
export function SpatialTextPanel({ timelineId, userId, sourceAssetId, playheadTime }: { timelineId?: string; userId?: string; sourceAssetId?: string; playheadTime: number }) {
  const [text, setText] = useState("在這裡輸入 3D 文字"); const [z, setZ] = useState(.5); const [point, setPoint] = useState({ x: .5, y: .5 }); const [message, setMessage] = useState("");
  const analyze = async () => { if (!sourceAssetId || !userId) return; const response = await fetch(`${API}/api/v1/media/${sourceAssetId}/analyze-spatial-text`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ user_id: userId, use_proxy: true }) }); setMessage(response.ok ? "正在建立逐幀深度圖與相機軌跡…" : "無法啟動空間追蹤"); };
  const save = async () => { if (!timelineId || !userId || !sourceAssetId) return; const response = await fetch(`${API}/api/v1/timelines/${timelineId}/spatial-text`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ user_id: userId, source_asset_id: sourceAssetId, text, ...point, z, start_time: playheadTime, end_time: playheadTime + 3, color: "#ffffff" }) }); setMessage(response.ok ? "空間文字已鎖定到攝影機與深度遮擋。" : "請先完成深度與相機追蹤。"); };
  return <section className="rounded-xl border border-sky-400/30 bg-zinc-950 p-4"><h2 className="text-sm font-semibold text-zinc-100">3D 空間文字追蹤</h2><p className="mt-1 text-xs text-zinc-400">拖曳文字定位，滾輪調整 Z 軸；前景會依深度圖遮擋文字。</p><input value={text} onChange={(event) => setText(event.target.value)} className="mt-3 w-full rounded border border-zinc-700 bg-zinc-900 px-2 py-1.5 text-xs text-white" /><div className="relative mt-3 aspect-video overflow-hidden rounded-lg border border-zinc-700 bg-[radial-gradient(circle_at_55%_40%,#334155,transparent_45%),linear-gradient(135deg,#111827,#020617)]" onWheel={(event) => { event.preventDefault(); setZ((value) => Math.max(0, Math.min(1, value - event.deltaY * .001))); }}><button type="button" onPointerDown={(event) => event.currentTarget.setPointerCapture(event.pointerId)} onPointerMove={(event) => { if (!event.currentTarget.hasPointerCapture(event.pointerId)) return; const rect = event.currentTarget.parentElement!.getBoundingClientRect(); setPoint({ x: Math.max(0, Math.min(1, (event.clientX - rect.left) / rect.width)), y: Math.max(0, Math.min(1, (event.clientY - rect.top) / rect.height)) }); }} className="absolute -translate-x-1/2 -translate-y-1/2 cursor-move text-2xl font-black text-white drop-shadow-[0_3px_3px_rgba(0,0,0,.9)]" style={{ left: `${point.x * 100}%`, top: `${point.y * 100}%`, transform: `translate(-50%,-50%) scale(${.72 + z * .7})` }}>{text}</button><span className="absolute bottom-2 right-2 rounded bg-black/50 px-2 py-1 text-[10px] text-sky-100">Z {z.toFixed(2)} · 滾輪調整</span></div><div className="mt-3 flex gap-2"><button onClick={() => void analyze()} disabled={!sourceAssetId || !userId} className="rounded border border-sky-300 px-2 py-1.5 text-xs text-sky-100 disabled:opacity-40">分析深度與相機</button><button onClick={() => void save()} disabled={!timelineId || !userId} className="rounded bg-sky-300 px-2 py-1.5 text-xs font-bold text-zinc-950 disabled:opacity-40">加入空間文字</button></div>{message && <p className="mt-2 text-xs text-sky-200">{message}</p>}</section>;
}
