"use client";

import { useEffect, useState } from "react";

import { useTimelineStore } from "@/features/editor/timeline-store";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
type Marker = { source_start: number; source_end: number; recommendation: "review_cut" | "b_roll"; reason: string; confidence_score: number; fluency_score: number; metrics?: Record<string, number> };
interface RecordState { status: "idle" | "queued" | "processing" | "completed" | "failed"; markers: Marker[]; gaze_correction?: { status?: string; output_key?: string; error?: string } | null; error?: string; }

export function TalkingHeadConfidencePanel({ timelineId, userId, sourceAssetId }: { timelineId: string; userId: string; sourceAssetId?: string }) {
  const applyMarkers = useTimelineStore((state) => state.applyTalkingHeadMarkers); const [gazeConsent, setGazeConsent] = useState(false); const [record, setRecord] = useState<RecordState>({ status: "idle", markers: [] });
  const refresh = async () => { const response = await fetch(`${API_URL}/api/v1/timelines/${timelineId}/talking-head-confidence?user_id=${encodeURIComponent(userId)}`); if (!response.ok) return; const next = await response.json() as RecordState; setRecord(next); if (next.status === "completed" && next.markers.length) applyMarkers(next.markers); };
  useEffect(() => { void refresh(); }, [timelineId, userId]);
  useEffect(() => { if (record.status !== "queued" && record.status !== "processing" && record.gaze_correction?.status !== "queued") return; const id = window.setInterval(() => void refresh(), 3000); return () => window.clearInterval(id); }, [record.status, record.gaze_correction?.status]);
  const run = async () => { if (!sourceAssetId) return; setRecord((current) => ({ ...current, status: "queued", error: undefined })); try { const response = await fetch(`${API_URL}/api/v1/timelines/${timelineId}/talking-head-confidence`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ user_id: userId, source_asset_id: sourceAssetId, confidence_threshold: 58, enable_gaze_correction: gazeConsent, confirm_gaze_correction: gazeConsent || undefined, use_proxy_for_gaze: true }) }); const data = await response.json() as { detail?: string }; if (!response.ok) throw new Error(data.detail ?? "無法建立 Talking-Head 分析"); } catch (error) { setRecord((current) => ({ ...current, status: "failed", error: error instanceof Error ? error.message : "無法建立 Talking-Head 分析" })); } };
  const working = record.status === "queued" || record.status === "processing" || record.gaze_correction?.status === "queued";
  return <section className="rounded-xl border border-amber-300/25 bg-zinc-950 p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="text-sm font-semibold text-amber-100">Talking-Head 自信強化</h2><p className="mt-1 text-xs text-zinc-400">分析眼神、頭部朝向、姿態動態與贅詞。紅色標記為建議裁切審閱；黃色提示適合用 B-Roll 覆蓋。</p></div><span className="rounded bg-amber-300/10 px-2 py-1 text-[10px] font-semibold text-amber-200">{working ? "分析中" : record.status === "completed" ? `${record.markers.length} 個建議` : record.status === "failed" ? "失敗" : "待分析"}</span></div><label className="mt-3 flex items-start gap-2 rounded bg-zinc-900 p-2 text-xs text-zinc-300"><input type="checkbox" checked={gazeConsent} onChange={(event) => setGazeConsent(event.target.checked)} className="mt-0.5" /><span><strong className="text-amber-100">我同意產生可撤銷的眼神校正衍生影片。</strong><br />僅微調開眼幀的眼部區域；原始素材不會被覆寫。</span></label><button type="button" disabled={!sourceAssetId || working} onClick={() => void run()} className="mt-3 rounded bg-amber-300 px-3 py-2 text-xs font-bold text-zinc-950 disabled:opacity-45">{working ? "正在分析畫面呈現…" : "分析並標記 Talking-Head"}</button>{!sourceAssetId && <p className="mt-2 text-xs text-amber-300">目前時間軸找不到來源影片。</p>}{record.gaze_correction?.status === "completed" && <p className="mt-2 text-xs text-emerald-200">眼神校正衍生視訊已完成；下一次最終導出將自動使用它。</p>}{record.gaze_correction?.status === "failed" && <p className="mt-2 text-xs text-rose-300">眼神校正未完成：{record.gaze_correction.error ?? "請檢查模型設定"}</p>}{record.error && <p className="mt-2 text-xs text-rose-300">{record.error}</p>}<div className="mt-3 space-y-1.5">{record.markers.slice(0, 4).map((marker, index) => <div key={`${marker.source_start}-${index}`} className={`rounded px-2 py-1.5 text-xs ${marker.recommendation === "review_cut" ? "bg-red-500/15 text-red-100" : "bg-amber-500/10 text-amber-100"}`}>{marker.recommendation === "review_cut" ? "建議裁切／重錄" : "建議 B-Roll 覆蓋"} · {marker.reason}</div>)}</div></section>;
}
